server:
  port: 8081
spring:
  application:
    name: mcp-filesystem-client
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-b28da8f6d2fd4addaa0b47a80274d8d8
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
      embedding:
        enabled: false # The DeepSeek API doesn't support embeddings, so we need to disable it.
    mcp:
      client:
        stdio:
          connections:
            filesystem: #
              command: 'npx' #
              args: #
                - '-y'
                - '@modelcontextprotocol/server-filesystem'
                - '/Users/habuma/mcp-playground'
          servers-configuration: classpath:mcp-servers.json
logging:
  level:
      org:
        zalando:
          logbook: TRACE


